
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mokleters
 */
public class modul7_6 extends javax.swing.JFrame {

    /**
     * Creates new form modul7_6
     */
    public modul7_6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanjangBalok = new javax.swing.JTextField();
        jLebarBalok = new javax.swing.JTextField();
        jTinggiBalok = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jSisiKubus = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jJariBola = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        jLabel14.setText("jLabel14");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel1.setText("Program Pencari Volume Bangun Ruang");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 10, 270, 40);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Swis721 Blk BT", 0, 11)); // NOI18N
        jLabel2.setText("Masukkan Panjang :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(26, 11, 126, 44);

        jLabel3.setFont(new java.awt.Font("Swis721 Blk BT", 0, 11)); // NOI18N
        jLabel3.setText("Masukkan Lebar     :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(26, 76, 126, 40);

        jLabel4.setFont(new java.awt.Font("Swis721 Blk BT", 0, 11)); // NOI18N
        jLabel4.setText("Masukkan Tingi      :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(26, 134, 126, 39);
        jPanel1.add(jPanjangBalok);
        jPanjangBalok.setBounds(170, 18, 90, 30);
        jPanel1.add(jLebarBalok);
        jLebarBalok.setBounds(170, 86, 90, 30);
        jPanel1.add(jTinggiBalok);
        jTinggiBalok.setBounds(170, 138, 90, 30);

        jLabel5.setFont(new java.awt.Font("Swis721 Blk BT", 0, 11)); // NOI18N
        jLabel5.setText("cm");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(270, 26, 18, 14);

        jLabel6.setFont(new java.awt.Font("Swis721 Blk BT", 0, 11)); // NOI18N
        jLabel6.setText("cm");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(270, 94, 18, 14);

        jLabel7.setFont(new java.awt.Font("Swis721 Blk BT", 0, 11)); // NOI18N
        jLabel7.setText("cm");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(270, 146, 18, 14);

        jButton3.setBackground(new java.awt.Color(102, 102, 255));
        jButton3.setFont(new java.awt.Font("Swis721 Blk BT", 0, 11)); // NOI18N
        jButton3.setText("Hitung");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(116, 179, 73, 23);

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mokleters\\Pictures\\images (4).jpg")); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(0, 0, 770, 420);

        jTabbedPane1.addTab("Balok", jPanel1);

        jPanel2.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Swis721 Blk BT", 0, 12)); // NOI18N
        jLabel8.setText("Masukkan Panjang Sisi");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(53, 8, 151, 25);
        jPanel2.add(jSisiKubus);
        jSisiKubus.setBounds(53, 44, 98, 36);

        jLabel9.setFont(new java.awt.Font("Swis721 Blk BT", 0, 10)); // NOI18N
        jLabel9.setText("cm");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(161, 56, 17, 13);

        jButton1.setFont(new java.awt.Font("Swis721 Blk BT", 0, 11)); // NOI18N
        jButton1.setText("Volume");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(53, 98, 77, 23);

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mokleters\\Pictures\\images (4).jpg")); // NOI18N
        jPanel2.add(jLabel13);
        jLabel13.setBounds(-5, 0, 400, 420);

        jTabbedPane1.addTab("Kubus", jPanel2);

        jPanel3.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Swis721 Blk BT", 0, 12)); // NOI18N
        jLabel10.setText("Masukkan Panjang Jari-jari");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(50, 19, 177, 32);
        jPanel3.add(jJariBola);
        jJariBola.setBounds(50, 57, 108, 35);

        jLabel11.setFont(new java.awt.Font("Swis721 Blk BT", 0, 12)); // NOI18N
        jLabel11.setText("cm");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(168, 66, 20, 15);

        jButton2.setFont(new java.awt.Font("Swis721 Blk BT", 0, 12)); // NOI18N
        jButton2.setText("Volume");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(50, 110, 81, 23);

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mokleters\\Pictures\\images (4).jpg")); // NOI18N
        jPanel3.add(jLabel15);
        jLabel15.setBounds(0, -22, 400, 470);

        jTabbedPane1.addTab("Bola", jPanel3);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 50, 400, 250);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int panjang, lebar, tinggi;
        panjang = Integer.parseInt(jPanjangBalok.getText());
        lebar=Integer.parseInt(jLebarBalok.getText());
        tinggi= Integer.parseInt(jTinggiBalok.getText());
        int hasil=panjang*lebar*tinggi;
        try {
            JOptionPane.showMessageDialog(null,"Volume Balok Adalah :"+hasil,"volume",JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error:"+e,"Gagal",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        float jari;
        jari= Integer.parseInt(jJariBola.getText());
        float hasil=(float)(4/3*3.14*jari*jari*jari);
        try {
            JOptionPane.showMessageDialog(null,"Volume Bola Adalah :"+hasil,"volume",JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error:"+e,"Gagal",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int sisi;
        sisi = Integer.parseInt(jSisiKubus.getText());
        int hasil=sisi*sisi*sisi;
        try {
            JOptionPane.showMessageDialog(null,"Volume Kubus Adalah :"+hasil,"volume",JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error:"+e,"Gagal",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modul7_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modul7_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modul7_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modul7_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modul7_6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JTextField jJariBola;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jLebarBalok;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jPanjangBalok;
    private javax.swing.JTextField jSisiKubus;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTinggiBalok;
    // End of variables declaration//GEN-END:variables
}
